const presets=[['默认竖屏',720,1280],['iPhone 15',1179,2556],['iPhone SE',750,1334],['安卓高清',1080,2400],['平板竖屏',1536,2048]];
const state={width:720,height:1280,zoom:100,size:135,x:50,y:68,scene:'default',character:'local-placeholder',characters:[{id:'local-placeholder',name:'请上传本地角色',src:'data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs='}],scenes:[]};
const $=id=>document.getElementById(id); const clamp=(n,a,b)=>Math.min(b,Math.max(a,n));
function renderCharacters(){ $('characterList').innerHTML=state.characters.map(c=>`<button class="character-row ${state.character===c.id?'selected':''}" data-character="${c.id}"><span><img src="${c.src}" alt=""></span><div><b>${c.name}</b><small>135 × 135</small></div><i>${state.character===c.id?'✓':''}</i></button>`).join(''); }
function renderScenes(){ const upload=$('sceneList').querySelector('.upload-card'); $('sceneList').querySelectorAll('[data-scene]:not([data-scene="default"])').forEach(n=>n.remove()); state.scenes.forEach(s=>{const b=document.createElement('button');b.className=`asset-card ${state.scene===s.id?'selected':''}`;b.dataset.scene=s.id;b.innerHTML=`<img src="${s.src}" alt=""><b>${s.name}</b><small>${s.width} × ${s.height}</small>`;$('sceneList').insertBefore(b,upload)}); document.querySelector('[data-scene="default"]').classList.toggle('selected',state.scene==='default'); }
function renderPresets(){ $('presetList').innerHTML=presets.map(p=>`<button class="${state.width===p[1]&&state.height===p[2]?'selected':''}" data-width="${p[1]}" data-height="${p[2]}"><span>${p[0]}</span><small>${p[1]} × ${p[2]}</small></button>`).join(''); }
function update(){ const frame=$('deviceFrame');frame.style.aspectRatio=`${state.width}/${state.height}`;frame.style.width=state.width/state.height>.8?'min(58vh,480px)':'min(43vh,360px)';$('resolutionLabel').textContent=`${state.width} × ${state.height}`;$('scene').style.transform=`scale(${state.zoom/100})`;const ch=state.characters.find(c=>c.id===state.character);if(ch){$('stageCharacter').src=ch.src;$('previewCharacter').src=ch.src;$('characterName').textContent=ch.name}$('stageCharacter').hidden=!!ch?.spine;if($('spineCharacter'))$('spineCharacter').hidden=!ch?.spine;['stageCharacter','spineCharacter'].forEach(id=>{if($(id))$(id).style.cssText+=`;width:${state.size}px;height:${state.size}px;left:${state.x}%;top:${state.y}%`});$('sizeValue').textContent=`${state.size} × ${state.size}`;$('characterSize').value=state.size;['zoomDock','zoomRange'].forEach(id=>$(id).value=state.zoom);['zoomDockValue','zoomValue'].forEach(id=>$(id).textContent=`${state.zoom}%`);$('posX').value=Math.round(state.x);$('posY').value=Math.round(state.y);const sc=state.scenes.find(s=>s.id===state.scene);$('builtIn').hidden=!!sc;$('scene').style.backgroundImage=sc?`url(${sc.src})`:'';renderCharacters();renderScenes();renderPresets();}
async function files(input,kind){for(const file of [...input.files]){const src=await new Promise(r=>{const fr=new FileReader();fr.onload=()=>r(fr.result);fr.readAsDataURL(file)});const img=await new Promise(r=>{const i=new Image();i.onload=()=>r(i);i.src=src});const item={id:`${kind}-${Date.now()}-${Math.random()}`,name:file.name.replace(/\.[^.]+$/,''),src,width:img.naturalWidth,height:img.naturalHeight};if(kind==='scene'){state.scenes.push(item);state.scene=item.id}else{state.characters.push(item);state.character=item.id}}update();}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));$('assetsPanel').hidden=b.dataset.tab!=='assets';$('devicePanel').hidden=b.dataset.tab!=='device'});
['sceneUpload','sceneUploadTop'].forEach(id=>$(id).onchange=e=>files(e.target,'scene'));['characterUpload','characterUploadTop'].forEach(id=>$(id).onchange=e=>files(e.target,'character'));
$('sceneList').onclick=e=>{const b=e.target.closest('[data-scene]');if(b){state.scene=b.dataset.scene;update()}};$('characterList').onclick=e=>{const b=e.target.closest('[data-character]');if(b){state.character=b.dataset.character;update()}};
$('presetList').onclick=e=>{const b=e.target.closest('[data-width]');if(b){state.width=+b.dataset.width;state.height=+b.dataset.height;$('customWidth').value=state.width;$('customHeight').value=state.height;update()}};$('applySize').onclick=()=>{state.width=clamp(+$('customWidth').value,240,4096);state.height=clamp(+$('customHeight').value,320,4096);update()};
$('characterSize').oninput=e=>{state.size=+e.target.value;update()};['zoomDock','zoomRange'].forEach(id=>$(id).oninput=e=>{state.zoom=+e.target.value;update()});$('posX').onchange=e=>{state.x=clamp(+e.target.value,0,100);update()};$('posY').onchange=e=>{state.y=clamp(+e.target.value,0,100);update()};$('reset').onclick=()=>{state.x=50;state.y=68;state.zoom=100;update()};$('preview').onclick=()=>{$('workspace').classList.toggle('is-playing');$('preview').textContent=$('workspace').classList.contains('is-playing')?'退出预览':'沉浸预览'};
let move={x:0,y:0},held=false;function stick(e){const r=$('joystick').getBoundingClientRect(),rad=r.width/2,dx=e.clientX-r.left-rad,dy=e.clientY-r.top-rad,d=Math.hypot(dx,dy),s=d>rad?rad/d:1;move={x:dx*s/rad,y:dy*s/rad};$('knob').style.transform=`translate(calc(-50% + ${move.x*31}px),calc(-50% + ${move.y*31}px))`;const target=$('stageCharacter');if(move.x<-.08)target.style.transform='translate(-50%,-50%) scaleX(-1)';else if(move.x>.08)target.style.transform='translate(-50%,-50%) scaleX(1)'}
$('joystick').onpointerdown=e=>{held=true;$('joystick').setPointerCapture(e.pointerId);stick(e)};$('joystick').onpointermove=e=>{if(held)stick(e)};function release(){held=false;move={x:0,y:0};$('knob').style.transform='translate(-50%,-50%)'}$('joystick').onpointerup=release;$('joystick').onpointercancel=release;
(function loop(){if(held){state.x=clamp(state.x+move.x*.42,4,96);state.y=clamp(state.y+move.y*.42,6,94);const target=$('stageCharacter');target.style.left=state.x+'%';target.style.top=state.y+'%';$('posX').value=Math.round(state.x);$('posY').value=Math.round(state.y)}requestAnimationFrame(loop)})();update();
